name: FlutterCora

repository: https://github.com/albinpk/flutter_cora

packages:
  - packages/*

sdkPath: .fvm/flutter_sdk

command:
  version:
    hooks:
      # Update the version in readme
      preCommit: ./scripts/preVersion.sh
