name: flutter_cora

description: "A simple Flutter package for separating UI and business logic using a view-controller pattern."

version: 0.0.1-dev.13

homepage: https://github.com/albinpk/flutter_cora/tree/dev/packages/flutter_cora
repository: https://github.com/albinpk/flutter_cora/tree/dev/packages/flutter_cora
issue_tracker: https://github.com/albinpk/flutter_cora/issues

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - mvc
  - view-controller
  - state-management
  - architecture
  - clean-code
