name: flutter_cora_riverpod

description: "A simple Flutter package for separating UI and business logic using a view-controller pattern."

version: 0.0.1-dev.5

homepage: https://github.com/albinpk/flutter_cora/tree/dev/packages/flutter_cora_riverpod
repository: https://github.com/albinpk/flutter_cora/tree/dev/packages/flutter_cora_riverpod
issue_tracker: https://github.com/albinpk/flutter_cora/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - mvc
  - riverpod
  - view-controller
  - architecture
  - clean-code
